# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: catalogo.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'catalogo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63\x61talogo.proto\"#\n\x13\x43onsultaNomeRequest\x12\x0c\n\x04nome\x18\x01 \x01(\t\"T\n\x0fProdutoResponse\x12\x0c\n\x04nome\x18\x01 \x01(\t\x12\r\n\x05preco\x18\x02 \x01(\x01\x12\x12\n\nquantidade\x18\x03 \x01(\x05\x12\x10\n\x08mensagem\x18\x04 \x01(\t\"+\n\x14\x43onsultaPrecoRequest\x12\x13\n\x0bprecoMaximo\x18\x01 \x01(\x01\"6\n\x10ProdutosResponse\x12\"\n\x08produtos\x18\x01 \x03(\x0b\x32\x10.ProdutoResponse\";\n\x17\x41tualizarEstoqueRequest\x12\x0c\n\x04nome\x18\x01 \x01(\t\x12\x12\n\nquantidade\x18\x02 \x01(\x05\"]\n\x18\x41tualizarEstoqueResponse\x12\x0c\n\x04nome\x18\x01 \x01(\t\x12\r\n\x05preco\x18\x02 \x01(\x01\x12\x12\n\nquantidade\x18\x03 \x01(\x05\x12\x10\n\x08mensagem\x18\x04 \x01(\t2\xcf\x01\n\x0f\x43\x61talogoService\x12\x37\n\rConsultarNome\x12\x14.ConsultaNomeRequest\x1a\x10.ProdutoResponse\x12:\n\x0e\x43onsultarPreco\x12\x15.ConsultaPrecoRequest\x1a\x11.ProdutosResponse\x12G\n\x10\x41tualizarEstoque\x12\x18.AtualizarEstoqueRequest\x1a\x19.AtualizarEstoqueResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'catalogo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONSULTANOMEREQUEST']._serialized_start=18
  _globals['_CONSULTANOMEREQUEST']._serialized_end=53
  _globals['_PRODUTORESPONSE']._serialized_start=55
  _globals['_PRODUTORESPONSE']._serialized_end=139
  _globals['_CONSULTAPRECOREQUEST']._serialized_start=141
  _globals['_CONSULTAPRECOREQUEST']._serialized_end=184
  _globals['_PRODUTOSRESPONSE']._serialized_start=186
  _globals['_PRODUTOSRESPONSE']._serialized_end=240
  _globals['_ATUALIZARESTOQUEREQUEST']._serialized_start=242
  _globals['_ATUALIZARESTOQUEREQUEST']._serialized_end=301
  _globals['_ATUALIZARESTOQUERESPONSE']._serialized_start=303
  _globals['_ATUALIZARESTOQUERESPONSE']._serialized_end=396
  _globals['_CATALOGOSERVICE']._serialized_start=399
  _globals['_CATALOGOSERVICE']._serialized_end=606
# @@protoc_insertion_point(module_scope)
