# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import catalogo_pb2 as catalogo__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in catalogo_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CatalogoServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ConsultarNome = channel.unary_unary(
                '/CatalogoService/ConsultarNome',
                request_serializer=catalogo__pb2.ConsultaNomeRequest.SerializeToString,
                response_deserializer=catalogo__pb2.ProdutoResponse.FromString,
                _registered_method=True)
        self.ConsultarPreco = channel.unary_unary(
                '/CatalogoService/ConsultarPreco',
                request_serializer=catalogo__pb2.ConsultaPrecoRequest.SerializeToString,
                response_deserializer=catalogo__pb2.ProdutosResponse.FromString,
                _registered_method=True)
        self.AtualizarEstoque = channel.unary_unary(
                '/CatalogoService/AtualizarEstoque',
                request_serializer=catalogo__pb2.AtualizarEstoqueRequest.SerializeToString,
                response_deserializer=catalogo__pb2.AtualizarEstoqueResponse.FromString,
                _registered_method=True)


class CatalogoServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ConsultarNome(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConsultarPreco(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AtualizarEstoque(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CatalogoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ConsultarNome': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsultarNome,
                    request_deserializer=catalogo__pb2.ConsultaNomeRequest.FromString,
                    response_serializer=catalogo__pb2.ProdutoResponse.SerializeToString,
            ),
            'ConsultarPreco': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsultarPreco,
                    request_deserializer=catalogo__pb2.ConsultaPrecoRequest.FromString,
                    response_serializer=catalogo__pb2.ProdutosResponse.SerializeToString,
            ),
            'AtualizarEstoque': grpc.unary_unary_rpc_method_handler(
                    servicer.AtualizarEstoque,
                    request_deserializer=catalogo__pb2.AtualizarEstoqueRequest.FromString,
                    response_serializer=catalogo__pb2.AtualizarEstoqueResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CatalogoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('CatalogoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CatalogoService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ConsultarNome(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CatalogoService/ConsultarNome',
            catalogo__pb2.ConsultaNomeRequest.SerializeToString,
            catalogo__pb2.ProdutoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConsultarPreco(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CatalogoService/ConsultarPreco',
            catalogo__pb2.ConsultaPrecoRequest.SerializeToString,
            catalogo__pb2.ProdutosResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AtualizarEstoque(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CatalogoService/AtualizarEstoque',
            catalogo__pb2.AtualizarEstoqueRequest.SerializeToString,
            catalogo__pb2.AtualizarEstoqueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
